### ISSUE TITLE
Machine.on is behaving as onEnter instead of onTransition

### ISSUE THREAD

**Issue by mpolichette** [shime/micro-machine#1]
The current code will call events based on the state we are entering instead of the transition.  It would be nicer if it was off of the transition.

In the README the example shows 
`machine.on('reset', function(){ ... });`

However this wouldn't work with the current code... instead, you would have to do
`machine.on('pending', function() { ... });`
Which doesn't really make sense to log 'resetting...' from anyway

**Comment by shime** [comment]
Thanks for reporting! Fixed and published the new version.
